[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:3000"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
